import {
  TechStackCategory,
  TechStackProficiency,
  type TechStackItem,
} from './types';

const frontendStackItems: TechStackItem[] = [
  {
    name: 'React',
    logo: '/tech-icons/react.svg',
    url: 'https://reactjs.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'reactjs',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'Next.js',
    logo: '/tech-icons/nextjs.svg',
    url: 'https://nextjs.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'nextjs2',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'Astro',
    logo: '/tech-icons/astro.svg',
    url: 'https://astro.build/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.hobby,
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'Flutter',
    logo: '/tech-icons/flutter.svg',
    url: 'https://flutter.dev/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'flutter',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'React Native',
    logo: '/tech-icons/react-native.svg',
    url: 'https://reactnative.dev/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.hobby,
    logoId: 'reactjs',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'Redux',
    logo: '/tech-icons/redux.svg',
    url: 'https://redux.js.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'redux',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'Redux Saga',
    logo: '/tech-icons/redux-saga.svg',
    url: 'https://redux-saga.js.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'reduxsaga',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'Tailwind CSS',
    logo: '/tech-icons/tailwind-css.svg',
    url: 'https://tailwindcss.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'tailwindcss',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'Zustand',
    logo: '/tech-icons/zustand.svg',
    url: 'https://github.com/pmndrs/zustand',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'React Query',
    logo: '/tech-icons/react-query.svg',
    url: 'https://react-query.tanstack.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'reactquery',
    categories: [TechStackCategory.frontend],
  },
  {
    name: 'ReactiveX',
    logo: '/tech-icons/rx.png',
    url: 'https://reactivex.io/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.frontend],
  },
];

const backendTechStackItems: TechStackItem[] = [
  {
    name: 'Apollo GraphQL',
    logo: '/tech-icons/apollo.svg',
    url: 'https://www.apollographql.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.backend],
  },
  {
    name: 'NestJS',
    logo: '/tech-icons/nestjs.svg',
    url: 'https://nestjs.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'nestjs',
    categories: [TechStackCategory.backend],
  },
  {
    name: 'PostgreSQL',
    logo: '/tech-icons/postgresql.svg',
    url: 'https://www.postgresql.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'postgresql',
    categories: [TechStackCategory.backend],
  },
  {
    name: 'MongoDB',
    logo: '/tech-icons/mongodb.svg',
    url: 'https://www.mongodb.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'mongodb',
    categories: [TechStackCategory.backend],
  },
  {
    name: 'Express',
    logo: '/tech-icons/express.svg',
    url: 'https://expressjs.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.backend],
  },
  {
    name: 'Redis',
    logo: '/tech-icons/redis.svg',
    url: 'https://redis.io/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'redis',
    categories: [TechStackCategory.backend],
  },
];

const langOrRuntimeStackItems: TechStackItem[] = [
  {
    name: 'TypeScript',
    logo: '/tech-icons/typescript.svg',
    url: 'https://www.typescriptlang.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'typescript',
    categories: [TechStackCategory.language],
  },
  {
    name: 'Node.js',
    logo: '/tech-icons/nodejs.svg',
    url: 'https://nodejs.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'nodejs',
    categories: [TechStackCategory.language],
  },
  {
    name: 'JavaScript',
    logo: '/tech-icons/javascript.svg',
    url: 'https://www.javascript.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'js',
    categories: [TechStackCategory.language],
  },
  {
    name: 'Dart',
    logo: '/tech-icons/dart.svg',
    url: 'https://dart.dev/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'dart',
    categories: [TechStackCategory.language],
  },
];

const specTechStackItems: TechStackItem[] = [
  {
    name: 'Graphql',
    logo: '/tech-icons/graphql.svg',
    url: 'https://graphql.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'graphql',
    categories: [TechStackCategory.spec],
  },
];

const devopsTechStackItems: TechStackItem[] = [
  {
    name: 'Docker',
    logo: '/tech-icons/docker.svg',
    url: 'https://www.docker.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'docker',
    categories: [TechStackCategory.devops],
  },
  {
    name: 'Terraform',
    logo: '/tech-icons/terraform.svg',
    url: 'https://www.terraform.io/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.hobby,
    categories: [TechStackCategory.devops],
  },
  {
    name: 'Ansible',
    logo: '/tech-icons/ansible.svg',
    url: 'https://www.ansible.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.hobby,
    categories: [TechStackCategory.devops],
  },
];

const miscTechStackItems: TechStackItem[] = [
  {
    name: 'Git',
    logo: '/tech-icons/git.svg',
    url: 'https://git-scm.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'git',
    categories: [TechStackCategory.misc],
  },
  {
    name: 'GitHub',
    logo: '/tech-icons/github.svg',
    url: 'https://github.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.misc],
  },
  {
    name: 'GitLab',
    logo: '/tech-icons/gitlab.svg',
    url: 'https://gitlab.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'gitlab',
    categories: [TechStackCategory.misc],
  },
  {
    name: 'Nx',
    logo: '/tech-icons/nx-dark.svg',
    url: 'https://nx.dev/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.misc],
  },
  {
    name: 'Turbo repo',
    logo: '/tech-icons/turbo-repo.svg',
    url: 'https://turborepo.org/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.misc],
  },
  {
    name: 'Firebase',
    logo: '/tech-icons/firebase.svg',
    url: 'https://firebase.google.com/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'firebase',
    categories: [TechStackCategory.misc, TechStackCategory.backend],
  },
  {
    name: 'Jest',
    logo: '/tech-icons/jest.svg',
    url: 'https://jestjs.io/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    logoId: 'jest',
    categories: [TechStackCategory.misc],
  },
  {
    name: 'Prisma',
    logo: '/tech-icons/prisma.svg',
    url: 'https://prisma.io/',
    projectIds: ['ffeline-blog'],
    proficiency: TechStackProficiency.professional,
    categories: [TechStackCategory.misc],
  },
];

export const allTechStackItems = [
  ...frontendStackItems,
  ...backendTechStackItems,
  ...devopsTechStackItems,
  ...specTechStackItems,
  ...langOrRuntimeStackItems,
  ...miscTechStackItems,
];
